# Generated by Django 4.1.1 on 2022-09-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layout',
            options={'ordering': ('site', 'pos'), 'verbose_name': 'Template', 'verbose_name_plural': '3. Templates'},
        ),
        migrations.AlterUniqueTogether(
            name='layout',
            unique_together={('site', 'pos')},
        ),
    ]
