# Generated by Django 4.1.1 on 2022-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0002_alter_layout_options_alter_layout_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='sort',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='sort',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='layouti18n',
            name='sort',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='orden'),
        ),
    ]
